export const STROOP = [
  { label: 'Red', value: 'red' },
  { label: 'Green', value: 'green' },
  { label: 'Blue', value: 'blue' },
  { label: 'Yellow', value: 'yellow' },
  { label: 'Pink', value: 'pink' },
  { label: 'Orange', value: 'orange' },
  { label: 'Blue', value: 'blue' },
  { label: 'Green', value: 'green' },
  { label: 'Blue', value: 'blue' },
  { label: 'White', value: 'white' },
  { label: 'Green', value: 'green' },
  { label: 'Yellow', value: 'yellow' },
  { label: 'Orange', value: 'orange' },
  { label: 'Blue', value: 'blue' },
  { label: 'White', value: 'white' },
  { label: 'Brown', value: 'brown' },
  { label: 'Red', value: 'red' },
  { label: 'Blue', value: 'blue' },
  { label: 'Yellow', value: 'yellow' },
  { label: 'Green', value: 'green' },
  { label: 'Pink', value: 'pink' },
  { label: 'Yellow', value: 'yellow' },
  { label: 'Green', value: 'green' },
  { label: 'Blue', value: 'blue' },
  { label: 'Red', value: 'red' }
]

export const STROOP_OPTIONS = ['red', 'green', 'blue', 'yellow', 'pink', 'orange', 'white', 'brown']

export const STROOP_RANDOM = [
  { label: 'Red', value: 'green' },
  { label: 'Green', value: 'yellow' },
  { label: 'Blue', value: 'white' },
  { label: 'Yellow', value: 'pink' },
  { label: 'Pink', value: 'orange' },
  { label: 'Orange', value: 'blue' },
  { label: 'Blue', value: 'red' },
  { label: 'Green', value: 'yellow' },
  { label: 'Blue', value: 'green' },
  { label: 'White', value: 'blue' },
  { label: 'Green', value: 'red' },
  { label: 'Yellow', value: 'blue' },
  { label: 'Orange', value: 'green' },
  { label: 'Blue', value: 'red' },
  { label: 'White', value: 'pink' },
  { label: 'Brown', value: 'blue' },
  { label: 'Red', value: 'yellow' },
  { label: 'Blue', value: 'pink' },
  { label: 'Yellow', value: 'green' },
  { label: 'Green', value: 'orange' },
  { label: 'Pink', value: 'red' },
  { label: 'Yellow', value: 'blue' },
  { label: 'Green',  value: 'orange' },
  { label: 'Blue', value: 'red' },
  { label: 'Red', value: 'green' }
]
